// src/lib/Editor.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';

  import { text } from '../store';

  let value: string = '';

  const u = text.subscribe((t) => (value = t));
  $: text.set(value);

  onDestroy(() => u());
</script>

<textarea class="h-full w-1/2 resize-none p-2 bg-dark-900" bind:value />

// components/Editor.vue
<script setup lang="ts">
const store = useStore();
</script>

<template>
    <div class="relative overflow-hidden text-sm">
        <textarea
            class="bg-transparent resize-none p-5 h-screen w-full"
            v-model="store.markup"
        ></textarea>
        <ModeSelection class="absolute bottom-0 right-0 m-2" />
    </div>
</template>
